"""empty message

Revision ID: eb939d5f8a59
Revises: 4f8edc7e024c
Create Date: 2025-02-17 15:06:59.260952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb939d5f8a59'
down_revision = '4f8edc7e024c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discriminator', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('discriminator')

    # ### end Alembic commands ###
