services:
  z-tech:
    build: .
    container_name: z-tech
    env_file: secrets.env
    environment:
      #- FLASK_ENV=development
      - PYTHONUNBUFFERED=True # Позволяет отслеживать процесс работы приложения в командной строке
      - DATABASE_URI=postgresql://postgres_user:postgres_password@postgres/postgres
      #- SECRET_KEY=obviouslynotsecret
      #- ONLY_DISCRIMINATOR=False
    restart: always
    volumes:
      - .:/Z-Technologies
    ports:
      - 5000:5000
    command: python3 main.py
    depends_on:
      - postgres
  postgres:
    container_name: postgresql-z-tech
    image: postgres:latest
    volumes:
      - postgres-z-tech-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    # For debugging:
    #ports:
    #  - 5432:5432

volumes:
  postgres-z-tech-data: